import pandas as pd
from sqlalchemy import create_engine
import mysql.connector

data=pd.read_csv("C:/Users/hp/Downloads/CSB/customer_shopping_behavior.csv")
df=pd.DataFrame(data)
pd.set_option("Display.max_columns",None)
print(df)
print(df.head())
print(df.info())
print(df.describe())
print(df.describe(include="all"))          #it will describe numerical data as well as string also
print(df.isnull().sum())
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))
print(df.isnull().sum())
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
print(df.columns)
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
print(df.columns)
labels=["young_adult","adult","middle_aged","senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)   #create a new column name "age_group" using the "age" column and labels that we provided
print(df[["age","age_group"]].head(20))
frequency_mapping={            #create a dictionary
    "Fortnightly":14,
    "Weekly":7,
    "Monthly":30,
    "Quarterly":120,
    "Bi-weekly":17,
    "Annually":365,
    "Every 3 Months":90
}
df["purchase_frequency_days"]=df["frequency_of_purchases"].map(frequency_mapping)     #create a new column "purchase_frequency_days" using existing column "frequency_of_purchases" and dictionary that we provided in map function
print(df[["purchase_frequency_days","frequency_of_purchases"]].head(20))
print(df[["discount_applied","promo_code_used"]].head(20))
print((df["discount_applied"]==df["promo_code_used"]).all())   #return true if all values are same
df=df.drop("promo_code_used",axis=1)
print(df.columns)


user = "dipu"
password = "1234"
host = "127.0.0.1"
port = 3307
database = "project_schema"

TABLE_NAME = "csb_table"
# CSV_FILE = "C:/Users/hp/Downloads/CSB/customer_shopping_behavior.csv"

try:
    engine = create_engine("mysql+pymysql://dipu:1234@127.0.0.1:3307/project_schema")
    print("Reading CSV file...")
    # df = pd.read_csv(CSV_FILE)
    print(len(df))
    print(f"Pushing data to MySQL table '{TABLE_NAME}'...")
    df.to_sql(
        name=TABLE_NAME,
        con=engine,
        if_exists="replace",   # or "replace" if you want to overwrite
        index=False
    )

    print("CSV imported successfully!")

except Exception as e:
    print("Error:", e)

#1----what is the total revenue generated by male vs female customers----------------
#2----which customer used a discount but still spent more than a purchase amount-----
#3----which are the top 5 products with the highest average rating-------------------
#4----compare the average purchase amount between standard and express shipping------
#5----Do subscribed customer spent more ? compare avg spent and total revenue between subscribed and non-subscribed customers--
#6----which 5 products have the highest percent of purchased with discount applied--
#7----segment customer into new, returning and loyal based on their total number of previous purchases and show the count of each purchases--
#8----what are the top 5 most purchased product within each category----------------
#    9----Are customers who are repeat buyers(more than 5 previous purchases) are likely to subscribe--
#10---what is the revenue contribution of each group--------------------------------